CREATE TABLE Customer (customerId INT NOT NULL,
	address VARCHAR(144),
	phone VARCHAR(24),
	fName VARCHAR(32),
	lName VARCHAR(32),
	PRIMARY KEY (customerId));
	
CREATE SEQUENCE SEQ_CUSTOMERID;

CREATE OR REPLACE TRIGGER TRG_CUSTOMERID
BEFORE INSERT ON Customer
FOR EACH ROW
BEGIN
	SELECT SEQ_CUSTOMERID.NEXTVAL
	INTO :NEW.customerId
	FROM DUAL;
END;
/

CREATE TABLE Gym (gymId INT NOT NULL,
	address VARCHAR(144),
	managerSsn INT NOT NULL,
	phone VARCHAR(24),
	PRIMARY KEY (gymId));
	
CREATE SEQUENCE SEQ_GYMID;

CREATE OR REPLACE TRIGGER TRG_GYMID
BEFORE INSERT ON Gym
FOR EACH ROW
BEGIN
	SELECT SEQ_GYMID.NEXTVAL
	INTO :NEW.gymId
	FROM DUAL;
END;
/

CREATE TABLE Equipment (equipmentId INT NOT NULL,
	name VARCHAR(32) NOT NULL,
	gymId INT NOT NULL,
	condition VARCHAR(16) NOT NULL,
	CONSTRAINT FK_EQUIPMENT_GYMID
	FOREIGN KEY(gymId) REFERENCES Gym(gymId));
		
CREATE SEQUENCE SEQ_EQUIPID;

CREATE OR REPLACE TRIGGER TRG_EQUIPID
BEFORE INSERT ON Equipment
FOR EACH ROW
BEGIN
	SELECT SEQ_EQUIPID.NEXTVAL
	INTO :NEW.equipmentId
	FROM DUAL;
END;
/